### PR TITLE
Cc reviewing my cities code

### PR DESCRIPTION
**Pull request by Ccourter11**
realized my mistakes

### CODE REVIEW

**Comment by Ccourter11** [comment]
Can yall check this code out and let me know if it runs correctly also for yall

**Review by blusanders — DISMISSED** [review]
Seeing everything in the console like you indicated. Looks like you're close on seeing it on the DOM.

**Review by blusanders — APPROVED** [review]
Pulled down code. Looks good on my end.

**Review by CheoR — APPROVED** [review]
Components pulling in correctly.

**Pull request merged**
